- name: Installing Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Removing previous app content
  ansible.builtin.file:
    path: "{{ APP_LOC }}"
    state: absent

- name: Creating app content
  ansible.builtin.file:
    path: "{{ APP_LOC }}"
    state: directory

- name: Fetching Extracting frontend scripts
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: "{{ APP_LOC }}"
    remote_src: yes

- name: Renaming each service with its parameter value
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Starting nginx service
  ansible.builtin.service:
    name: nginx
    state: restarted